version: '2.2'

networks: 
  mynetwork:
    name: mynetwork
    attachable: true

services:
  # NGINX API Gateway to limit API quotas on a user
  nginx-api-gateway:
    container_name: nginx-api-gateway
    build:
      context: ./
      dockerfile: ./docker/nginx-api-gateway/Dockerfile
    image: nginx-api-gateway
    ports:
      - 88:80
      - 8080:8080
      - 443:443
    volumes:
      - type: bind
        source: ./services/nginx-api-gateway/nginx/conf.d
        target: /etc/nginx/conf.d/
    networks:
      - mynetwork
    depends_on:
      - nginx-quota-simulator

  # Frontend NGINX Quota Simulator
  nginx-quota-simulator:
    container_name: nginx-quota-simulator
    build:
      context: ./
      dockerfile: ./docker/nginx-quota-simulator/Dockerfile
    image: nginx-quota-simulator
    ports:
      - 11001:80
      - 11002:443
    volumes:
      - type: bind
        source: ./services/nginx-quota-simulator/conf.d
        target: /etc/nginx/conf.d
      - type: bind
        source: ./services/nginx-quota-simulator/content
        target: /usr/share/nginx/html/
    networks:
      - mynetwork
    depends_on:
      - nginx-quota-limiter

  # Backend NGINX Quota Limiter for Distributed API Gateways
  nginx-quota-limiter:
    container_name: nginx-quota-limiter
    build:
      context: ./
      dockerfile: ./docker/nginx-quota-limiter/Dockerfile
    image: nginx-quota-limiter
    ports:
      - 12001:12001
    volumes:
      - type: bind
        source: ./services/nginx-quota-limiter
        target: /var/www/nginx-quota-limiter/
    networks:
      - mynetwork
    depends_on:
      - dynamodb

  # Backend NGINX Quota Limiter with DB for Distributed API Gateways
  nginx-quota-limiter-w-db:
    container_name: nginx-quota-limiter-w-db
    build:
      context: ./
      dockerfile: ./docker/nginx-quota-limiter-w-db/Dockerfile
    image: nginx-quota-limiter-w-db
    ports:
      - 12002:12002
    volumes:
      - type: bind
        source: ./services/nginx-quota-limiter-w-db
        target: /var/www/nginx-quota-limiter-w-db/
    networks:
      - mynetwork
    depends_on:
      - dynamodb

  # The Amazon Web Services database system that supports data structures and 
  # key-valued cloud services. It allows users the benefit of auto-scaling, 
  # in-memory caching, backup and restore options for all their internet-scale
  # applications using DynamoDB.
  dynamodb:
    image:  amazon/dynamodb-local
    container_name: key-value-store
    hostname: dynamodb
    # restart: always
    volumes:
      - type: bind
        source: ./services/dynamodb/data
        target: /home/dynamodblocal/data
    ports:
      - 8000:8000
    command: "-jar DynamoDBLocal.jar -sharedDb --port 8000 -dbPath /home/dynamodblocal/data/"
    networks:
      - mynetwork

  # Sample object storage Service
  sample-object-storage-service:
    container_name: sample-object-storage-service
    build:
      context: ./
      dockerfile: ./docker/sample-object-storage-service/Dockerfile
    image: sample-object-storage-service
    ports:
      - 13001:80
    volumes:
      - type: bind
        source: ./services/sample-object-storage-service/conf.d
        target: /etc/nginx/conf.d/
    networks:
      - mynetwork

  # Sample Chat Service
  sample-chat-service:
    container_name: sample-chat-service
    build:
      context: ./
      dockerfile: ./docker/sample-chat-service/Dockerfile
    image: sample-chat-service
    ports:
      - 14001:80
    volumes:
      - type: bind
        source: ./services/sample-chat-service/conf.d
        target: /etc/nginx/conf.d/
    networks:
      - mynetwork

