version: '2.2'

services:
  nginx-quota-on-single-apigw:
    container_name: nginx-quota-on-single-apigw
    build:
      context: ./../../
      dockerfile: ./examples/01-quota-per-user-on-single-apigw/docker/Dockerfile
    image: nginx-quota-on-single-apigw
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - type: bind
        source: ./../../common/etc/nginx/oidc/
        target: /etc/nginx/oidc/
      - type: bind
        source: ./../../common/quota-core/
        target: /etc/nginx/quota/
      - type: bind
        source: ./service/etc/nginx/conf.d/
        target: /etc/nginx/conf.d/
      - type: bind
        source: ./../../common/quota-simulator/
        target: /usr/share/nginx/quota/
